title: Mahsa Soleimani
description: Mahsa's blog!
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark


url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
